name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint the codebase
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
        args: -E goimports -E godot
    - name: Build the Docker image
      run: |
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

        docker buildx build \
          --load \
          --target release \
          --cache-from ${GITHUB_REPOSITORY}-cache \
          --build-arg VERSION=${GITHUB_SHA} \
          --build-arg COMMIT=${GITHUB_SHA} \
          --build-arg DATE=${DATE} \
          --build-arg REPOSITORY=${GITHUB_REPOSITORY} \
          -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} \
          -f Dockerfile.buildkit .

        docker run -it --rm ${GITHUB_REPOSITORY}:${GITHUB_SHA} -v
